version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mariadata:/bitnami/mariadb
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:1.7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_FOLDER_INSTALL=install-dev
      - PRESTASHOP_FOLDER_ADMIN=admin-dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./prestadata:/bitnami/prestashop
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local